version: '3'
services:
  mysqlindocker:
    restart: always
    container_name: mysqlindocker
    image: mysql
    environment:
      MYSQL_DATABASE: bowler
      MYSQL_ROOT_PASSWORD: ueducation
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  bowler:
    restart: on-failure
    build: ./
    expose:
      - "10222"
    ports:
      - 10222:10222
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysqlindocker
